apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: frontend
spec:
  replicas: 3  # Fixed typo
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app1
          image: ganesh6498/sample1:latest
          ports:
            - containerPort: 80  # Fixed key name

---


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
